### ISSUE TITLE
Support Flutter v2.0

### ISSUE THREAD

**Issue by juanagu** [jonataslaw/readmore#14]
Hello I'm trying to use readmore with the new stable flutter version but I have the next error:

`  ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/readmore-1.0.1/lib/readmore.dart:82:58: Error: No named parameter with the name 'nullOk'.
            widget.locale ?? Localizations.localeOf(context, nullOk: true);
                                                             ^^^^^^
`

**Comment by epynic** [comment]
check https://github.com/epynic/readmore/tree/patch-1

**Comment by karabanovbs** [comment]
duplicate #13

**Comment by sirius53** [comment]
I Have duplicate error when will be solve this problem

**Comment by sajanyamaha** [comment]
> check https://github.com/epynic/readmore/tree/patch-1
> 
> ```
>   readmore:
>     git: 
>       url: git://github.com/epynic/readmore
> ```

when will this change be published ?

**Comment by juanagu** [comment]
#15
