### ISSUE TITLE
What does colorClickableText do?

### ISSUE THREAD

**Issue by ronytesler** [jonataslaw/readmore#20]
I don't see that color anywhere in my text.
It doesn't change the color of 'trimCollapsedText'.
I have to set moreStyle if I want to change 'trimCollapsedText' (not sure why it's called moreStyle if it affects 'trimCollapsedText'. I'd expect it to be called trimCollapsedTextStyle or something similar.

**Comment by Rishab-ms** [comment]
that's just the color of the trim collapsed text and trim expanded text.

**Comment by sahibjotsaggu** [comment]
`colorClickableText` doesn't seem to do anything: 
![Screenshot 2023-06-17 at 8 03 17 PM](https://github.com/jonataslaw/readmore/assets/8991960/786a5afd-99ae-4bde-a686-50f883e4aaeb)

And it doesn't accept a `TextStyle` because it's type is `Color`, not `TextStyle`

**Comment by sahibjotsaggu** [comment]
I tested #35 locally and it works. Can we merge #35?

**Comment by jonataslaw** [comment]
Fixed in [3.0.0](https://github.com/jonataslaw/readmore/releases/tag/3.0.0)
