### ISSUE TITLE
Add support for Selectable Text

### ISSUE THREAD

**Issue by prateekmedia** [jonataslaw/readmore#33]
It would be good if this package support selectable text as it is needed in many case.

**Comment by iqfareez** [comment]
To make the text selectable, wrap the `ReadMoreText` with [`SelectionArea`](https://api.flutter.dev/flutter/material/SelectionArea-class.html).

![image](https://user-images.githubusercontent.com/60868965/223088997-877e3c4d-8794-48e5-8fad-b39549205210.png)

**Comment by prateekmedia** [comment]
Nice, Thanks!
