### ISSUE TITLE
Error when collapsing on an emoji

### ISSUE THREAD

**Issue by LeGoffMael** [jonataslaw/readmore#39]
When the last character of the line that is collapsed is an emoji, an error is thrown :

```
════════ Exception caught by painting library ══════════════════════════════════
The following ArgumentError was thrown while building a TextSpan:
Invalid argument(s): string is not well-formed UTF-16
```

**Comment by LeGoffMael** [comment]
This error occurs only when a `preDataText` param is specified

**Comment by neo1125** [comment]
I guess this is the problem

https://github.com/dart-lang/sdk/issues/35798

`widget.data.substring(0, endIndex)` => `String.fromCharCodes(widget.data.runes, 0, endIndex)`

**Comment by Faiizii** [comment]
Can you please upload minimum reproducible code?
