### ISSUE TITLE
[Feature Request] Add url detection and launch support

### ISSUE THREAD

**Issue by DennisAshford** [jonataslaw/readmore#42]
Love this package, and it works great! But would be awesome to have url detection and launch url support within the package. 

Edit: It appears launch url was added to the last merge, but it is not working on the main package.

**Comment by maRci002** [comment]
FYI, this is available in PR #54

https://github.com/jonataslaw/readmore/assets/8436039/3c7fc530-e550-4636-8de7-367cfe6ba9bd
