### ISSUE TITLE
override the onTap method

### ISSUE THREAD

**Issue by jaydip-pawar** [jonataslaw/readmore#46]
If user wants to perform some other activity without extending the text, then user will not able to do this with current code, We can make a optional parameter where user can override the existing onTap method and can perform other task.

**Comment by hashirshoaeb** [comment]
I have similar use case. callback does help in adding the functionality but not with override.

**Comment by hashirshoaeb** [comment]
Do you have any API proposal?

**Comment by hashirshoaeb** [comment]
https://github.com/Blocship/readmore

**Comment by jonataslaw** [comment]
Fixed in [3.0.0](https://github.com/jonataslaw/readmore/releases/tag/3.0.0)

You can set "isExpandable: false"
