### ISSUE TITLE
Web Suport

### ISSUE THREAD

**Issue by PaulRedFoxCode** [jonataslaw/readmore#7]
I use your package for an website app. If I build for Android and windows is working, for the web it`s a simple text.
Can you check your package for web-support?
Thank you for your work!

**Comment by karabanovbs** [comment]
[flutter issue](https://github.com/flutter/flutter/issues/65940)

**Comment by maRci002** [comment]
It seems flutter/engine#34085 PR did fix the issue it is available in Flutter 3.7.0 stable release.

**Comment by jonataslaw** [comment]
Closing it, since the problem is not present in current version.
