### ISSUE TITLE
semantics is not recognized (reed more) 

### ISSUE THREAD

**Issue by abdalazeeza** [jonataslaw/readmore#73]
please add  semantics to read mroe text or add ability to make user can pass WidgetBuilder

**Comment by maRci002** [comment]
> please add semantics

I think package already supports it
https://github.com/jonataslaw/readmore/blob/a29db314efdc6b7cfe523c5972a57b377b3a1703/lib/readmore.dart#L158

**Comment by abdalazeeza** [comment]
ok the tester is reported it but i check it now its reconized 
tnank you for your response
